/**
 * @thelot.h
 * @version 1.0
 *
 * @section LICENSE
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License as
 * published by the Free Software Foundation; either version 2 of
 * the License, or (at your option) any later version.
 *
 * @section DESCRIPTION
 * Header for thelot library. A Gym is generated by inheriting a Lot.
 * During the gym's lifetime it may add members. Prior to program closing
 * it may destroy the gym by running demolition function.  
 */

#ifndef THELOT_H
#define THELOT_H

#include <iostream>
#include <vector>
#include <random>

/**
 * @class Lot
 * @brief Lot is a 40 sq foot plot of land with an area.
 *   
 * Lot's members will be protected. Required users of 
 * the lot to inherit. 
*/

class Lot {

protected:
   
  /**
   * @brief Constructor 
  */
  Lot();

public:
  
  /**
   * @brief Get area of Lot.
   * @return Area of lot.
  */
  int getArea();
 
  /**
   * @ brief Set area of Lot
   *
  */
  virtual void setArea(int a);

private:
  int area; /*!< units in sq-ft. */

};

/**
 * @class Gym
 * @brief Gym built on the Lot that has a single owner, equipments, and active_members.
*/
class Gym: protected Lot {

private: 

  std::string owner;
  int numEquipment;
  int numMembers; 
  int area; 

public:
 
  /** 
   * @brief Construct Gym object. No initialization parameters required. 
  */
  Gym(); // explicitly default
  
  /**
   * @brief Construct Gym object. Owner nameinitialization.
  */
  Gym(std::string name);


  /**
   * @brief Get gym owner name.
   * @return Name of owner.
  */
  std::string getOwnerName();

  /**
   * @brief Get number of equipment in gym.
   * @return Number of exercise machine.
  */
  std::string getEquipmentCount();
  
 /**
   * @brief Get number of active members in gym.
   * @return Number of active members.
  */
  std::string getMembersCount();


 /**
   * @brief Set area of gym
   * The area can only be increased. 
  */
  virtual void setArea(int a) override final ;
  

 /**
   * @brief Demolition building 
   * Destroy the building if the gym is empty 
   * @returns boolean value informing caller if the demolition was successful
  */
  bool demolition()  ;

 /**
   * @brief Add new member to gym.
   * Increments numMembers variable. 
  */
  void addMember();

 /**
   * @brief Remove member from  gym.
   * Decrements numMembers variable. 
  */
  void removeMember();

};

/**
 *@brief Generate a random boolean state.
 *@returns boolean value.
*/
bool random_bool();

#endif
